---

- include_vars: "{{ docker_package }}.yml"

- name: Install docker
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"

- name: Start docker
  service: name=docker enabled=yes state=started

- meta: flush_handlers

- include_tasks: swarm.yml
  when: docker_swarm_create_cluster

- name: Create logrotate config for docker container logs
  template:
    src:   docker-container.logrotate.j2
    dest:  /etc/logrotate.d/docker-container-logs
    mode:  0644
  when: docker_container_logs_rotate

#TODO: remove once applied to all env
- name: Remove existing SELinux context
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}/containers/*/*-json.log"
    setype: container_log_t
    state: absent

#TODO: remove once applied to all env
- name: Remove existing SELinux context
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}/containers/.*/.*\\.log"
    setype: container_log_t
    state: absent

#TODO: remove once applied to all env
- name: Set SELinux context for containers
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}/containers(/.*)?"
    setype: container_var_lib_t
    state: absent

- name: Set SELinux context for docker
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}(/.*)?"
    setype: container_var_lib_t
    state: present

- name: Set SELinux context for log files for logrotate
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}/containers/.*/.*\\.log"
    setype: container_log_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: "restorecon -rv {{ docker_data_root }}/containers"
