---
- name: Allow logrotate to access container files
  command: setsebool -VP logrotate_read_inside_containers 1
  when: docker_container_logs_rotate

- name: Set SELinux context for docker
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}(/.*)?"
    setype: container_var_lib_t
    state: present

- name: Set SELinux context for docker containers
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}/containers(/.*)?"
    setype: container_file_t
    state: present

- name: Set SELinux context for log files for logrotate
  sefcontext:
    ftype: a
    target: "{{ docker_data_root }}/containers/.*/.*\\.log"
    setype: container_log_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: "restorecon -rv {{ docker_data_root }}"
