---

## swarm-manager
- name: Set docker swarm manager container command for consul backend
  set_fact: 
    docker_swarm_manager_command_args:
      "-H :{{ docker_swarm_port }} --replication \
      --advertise {{ docker_swarm_host_ip }}:{{ docker_swarm_port }}"
  when: docker_swarm_manager

## Fix for the issue cause due to the latest version of websocket client, docker operation were failing for docker-py lib
- name: install websocket-client 0.59.0 version
  shell: pip install websocket-client==0.59.0

- name: Start swarm manager container
  docker_container:
    name:    swarm-manager
    image:   "swarm:{{ docker_swarm_image_version }}"
    command: "{{ docker_swarm_manager_command }}"
    expose:
      - "{{ docker_swarm_port }}"
    ports:
      - "{{ docker_swarm_port }}:{{ docker_swarm_port }}"
    restart_policy: "unless-stopped"
    state:   started
  when: docker_swarm_manager


## swarm-node
- name: Set docker swarm node container command for consul backend
  set_fact: 
    docker_swarm_node_command_args:
      "--advertise {{ docker_swarm_host_ip }}:{{ docker_engine_port }}"
  when: docker_swarm_node

- name: Start swarm node container
  docker_container:
    name:    swarm-node
    image:   "swarm:{{ docker_swarm_image_version }}"
    command: "{{ docker_swarm_node_command }}"
    restart_policy: "unless-stopped"
    state:   started
  when: docker_swarm_node
